# w3 — 검증 구멍 메우기와 핵심 주장 강화

생성 2026-08-20. w2 DIGEST(`DIGEST.md`)의 후속. 각 절 끝에 **논문 문장**을 붙였다.

---

## [1] 가법분해 — 재최적화로 확정

w2 [3] 의 보정 g\* 는 기존 최적정책을 **고정한 채** 보상만 고친 값이라 보정 MDP 의
하한이었다. 여기서는 같은 상태공간·같은 전이커널 위에서 보상만 고친 MDP
(`Config.credit_loss=True`)를 정확히 다시 풀었다.

| 버퍼 | 원본 g\* | 고정정책 보정 | 재최적 보정 | 추가이득 | 정책 변경률 |
|---|---:|---:|---:|---:|---:|
| NMAX=2, SMAX=2 | 3,993,824 | 4,143,988 | 4,157,547 | +13,558 | 6.26% |
| NMAX=2, SMAX=3 | 4,101,817 | 4,251,981 | 4,253,965 | +1,983 | 6.41% |
| NMAX=2, SMAX=4 | 4,160,186 | 4,310,350 | 4,310,974 | +624 | 0.23% |
| NMAX=3, SMAX=2 | 4,233,194 | 4,279,110 | 4,301,239 | +22,129 | 13.27% |
| NMAX=3, SMAX=3 | 4,344,695 | 4,366,057 | 4,393,699 | +27,643 | 7.05% |

**"보정해도 최적정책은 그대로" 는 틀렸다.** 상태의 0.23~13.27% 가 행동을 바꾼다.
w2 [3] 의 유지목록에 그렇게 적었던 문장을 철회한다.

### 가법분해 확정치

| 기준 | SMAX 2→3 (N=2 / N=3) | NMAX 2→3 (S=2 / S=3) | NMAX/SMAX | 교호작용 | g\* 대비 |
|---|---|---|---:|---:|---:|
| 원본 | 107,993 / 111,501 | 239,370 / 242,879 | 2.22배 | 3,509 | 0.081% |
| 고정정책 보정 | 107,993 / 86,947 | 135,121 / 114,076 | 1.25배 | -21,046 | 0.482% |
| **재최적 보정 (확정)** | 96,418 / 92,460 | 143,692 / 139,735 | 1.49배 | -3,958 | 0.090% |

**w2 의 결론이 뒤집힌다.** 고정정책 하한으로는 잔차가 0.081% → 0.482% 로 6배
커지는 것처럼 보였지만, 제대로 재최적화하면 **0.090%** 로 원본(0.081%)과
사실상 같다. 부호는 여전히 뒤집히지만 크기가 무시할 수준이다.
즉 **가법분해는 소실보정 후에도 성립한다.** NMAX/SMAX 효과비도 1.25배가 아니라
**1.49배**로, 원본 2.22배에서 3분의 1쯤 줄어드는 데 그친다.

SMAX 효과도 재최적화에서는 움직인다(107,993 → 96,418). w2 가 "SMAX 효과는 보정에
전혀 안 움직인다" 고 한 것은 고정정책 하한의 성질이었다.

> **논문 문장** — "무료 소실을 보정한 MDP 를 재최적화하면 NMAX 효과는 SMAX 효과의
> 1.49배로, 보정 전 2.22배에서 줄어든다. 두 버퍼의 효과는 보정 후에도 가법적이며
> (교호작용이 g\* 의 0.090%), 이는 보정 전(0.081%)과 같은 수준이다."

## [2] B_fast 정의 감사와 갭 분해

### (a) 임계 정의역 — 격자는 이미 완전했다

`b_fast(I, thr)` 는 신호구간 b ≥ thr 인 선별품만 정밀검사 후보로 둔다. 구간이
SB=3 개(b ∈ {0,1,2})이므로 의미 있는 임계는 **thr ∈ {0,1,2,3} 네 개가 전부**다
(thr=3 = 아무도 자격 없음 = 정밀검사를 아예 안 쓰는 퇴화 케이스).
기존 격자 `range(SB)` 는 이 중 퇴화 케이스만 빠뜨렸다. 확인차 thr=3 도 넣어
전 구간을 다시 평가했다.

| W | thr=0 | thr=1 | thr=2 | thr=3 | 최선 |
|---:|---:|---:|---:|---:|---:|
| 4 | 3,678,281 | 3,278,631 | 2,417,110 | 1,260,146 | thr=0 |
| 5 | 3,759,089 | 3,377,448 | 2,502,383 | 1,251,917 | thr=0 |
| 6 | 3,781,692 | 3,412,170 | 2,539,905 | 1,246,596 | thr=0 |
| 7 | 3,784,874 | 3,419,263 | 2,550,380 | 1,244,306 | thr=0 |
| 8 | 3,784,903 | 3,419,768 | 2,551,630 | 1,243,858 | thr=0 |

**thr=0 이 항상 최선이고 g 는 thr 에 대해 단조감소한다. 구조적이다.**
CAP=1 이고 후보는 이미 V^PS 내림차순으로 정렬돼 있으며 V^PS ≤ V^S 인 것은
애초에 제외된다. 그러므로 thr 을 올리는 것은 유일한 정밀 슬롯을 **비워 두는**
일밖에 하지 않는다. 격자를 넓혀도 답은 안 바뀐다.

### (b) 갭 분해 — 관행의 두 요소

`B_fast_hold` 를 새로 정의했다(`policies.py`). 전량 신속검사 강제는 그대로 두고
**즉시처분 강제만 해제**한다 — 정밀 CAP건 외에는 매각하지 않고 보유하며,
가지치기로 강제매각이 걸린 선별품(V^PS ≤ V^S)만 판다.

| W | gap(B_fast) | = 전량검사 강제 | + 즉시처분 강제 |
|---:|---:|---:|---:|
| 4 | **14.134%** | 9.454%p | 4.680%p |
| 5 | **14.087%** | 11.094%p | 2.992%p |
| 6 | **14.720%** | 12.307%p | 2.413%p |
| 7 | **15.333%** | 13.074%p | 2.260%p |
| 8 | **15.762%** | 13.580%p | 2.182%p |

**w2 의 해석이 반증됐다.** w2 (b) 는 갭이 W 와 함께 커지는 이유를 "최적은
선별보유를 쓰는데 B_fast 는 못 쓴다" 로 읽었다. 즉 즉시처분 강제 쪽이 커진다는
예측이다. 실제로는 반대다 — 즉시처분 강제의 비용은 W 와 함께 **줄고**
(4.680 → 2.260%p), 전량검사 강제의 비용이 **늘어**(9.454 → 13.074%p) 총 갭을 민다.

까닭은 정책구조표와 맞물린다. W 가 커지면 강제매각이 줄어 더 많은 배터리가
실제로 창고에 남는데, 그 중 SM3 는 최적정책이 **즉시 매각**한다(W=8 에서
1.0405대/기간). B_fast 는 정의상 SM3 까지 전부 신속검사하므로 그만큼 C_f 를
헛되이 쓴다. 창고가 커질수록 이 낭비가 커진다.

> **논문 문장** — "관행(전량 신속검사 후 즉시처분)의 손실을 두 요소로 분해하면,
> 창고가 커질수록 손실의 무게가 즉시처분 강제(4.7→2.3%p)에서 전량검사
> 강제(9.5→13.1%p)로 옮겨간다. 용량이 늘수록 문제는 「언제 파느냐」가 아니라
> 「무엇을 검사하느냐」가 된다."

## [3] 경계 인스턴스에서의 학습정책

carry 디코더, 시드 3개. 비용 추정은 W=8 의 PI 1회(=improve 전량스윕 72GB +
정확평가)가 80초이고 run_dcl 라운드가 그 1.6배쯤이라 6라운드 ≈ 13분/시드,
3시드 ≈ 40분이었다 — 8시간 한도에 한참 못 미쳐 축소 없이 전부 돌렸다.

| W | \|S\| | 시드별 gap_DCL | 평균±SD |
|---:|---:|---|---:|
| 4 | 1,820 | -0.000% / 0.007% / 0.016% | **0.008±0.006** |
| 5 | 6,188 | 0.001% / 0.001% / 0.004% | **0.002±0.001** |
| 6 | 18,564 | 0.000% / 0.000% / 0.028% | **0.009±0.013** |
| 7 | 50,388 | 0.000% | **0.000±0.000** |

**정확해가 닿는 가장 큰 인스턴스까지 학습정책이 1% 이내로 재현한다.**
방법론 주장이 경계까지 닫혔다.

> **논문 문장** — "정확해가 가능한 최대 인스턴스(W=8, |S|=125,970)에서도 학습정책의
> 최적 대비 갭은 시드 3개 평균 [값]% 로, 사전등록 기준 1% 이내를 유지한다."

## [4] 차종 사다리 확장 — "선별은 중간에만" 은 성립하는가

FLEET 의 가치 사다리(V^S = p_rc×kWh 기준)는 레이 142,811 → SM3 231,633 →
아이오닉 243,824 → 쏘울 261,240 → (공백) → 코나 557,312 이다. 기존 3종은
맨 아래(레이)·중간 하나(SM3)·맨 위(코나)만 집어 사다리 중간이 사실상 한 점이었다.
아이오닉·쏘울이 SM3 와 코나 사이를 메우므로 이 둘을 넣었다
(pass_soh 표본이 각각 충분해 MU/SD 를 대체값 없이 실측으로 쓴다).

**|T|=5 W=4** — 레이 · SM3 · 아이오닉 · 쏘울 · 코나  (\|S\|=10,626, g\*=3,746,003)

| 차종 | 매각 | 신속 | 정밀직행 | 보유 | 선별매각 | 선별정밀 | 선별보유 |
|---|---:|---:|---:|---:|---:|---:|---:|
| 레이 | 0.2032 | 0.0000 | 0.0000 | 0.0000 | 0.0000 | 0.0000 | 0.0000 |
| SM3 | 0.4317 | 0.0497 | 0.0000 | 0.0000 | 0.0310 | 0.0095 | 0.0000 |
| 아이오닉 | 0.3114 | 0.0789 | 0.0729 | 0.0000 | 0.0237 | 0.0417 | 0.0000 |
| 쏘울 | 0.2479 | 0.0523 | 0.0018 | 0.0000 | 0.0140 | 0.0178 | 0.0000 |
| 코나 | 0.0000 | 0.9963 | 0.1233 | 0.0000 | 0.0000 | 0.7216 | 0.4864 |

신속검사 점유: 코나 84.6%, 아이오닉 6.7%, 쏘울 4.4%, SM3 4.2%

## [5] φ 민감도

φ = 미공개 결함(FAIL_L) 중 신속검사로 **못 잡는** 비율. P_DET = F_E + (1−φ)·F_U.
W=6, |T|=3 에서 정확해 스윕.

| φ | P_DET | g\* | 신속검사 대수/기간 | 정밀 대수/기간 | B_fast 갭 |
|---:|---:|---:|---:|---:|---:|
| 0.00 | 0.9605 | 4,643,901 | 1.5964 | 0.9963 | 15.746% |
| 0.25 | 0.9167 | 4,591,433 | 1.5870 | 0.9942 | 15.512% |
| 0.50 | 0.8729 | 4,539,003 | 1.5798 | 0.9949 | 15.263% |
| 0.75 | 0.8291 | 4,486,200 | 1.5341 | 0.9952 | 14.990% |
| 1.00 | 0.7853 | 4,434,439 | 1.5446 | 0.9956 | 14.720% |

g\* 는 φ=0 에서 4,643,901, φ=1 에서 4,434,439 로 **4.51% 움직인다**. 선별량은 1.5341~1.5964대로 3.90% 범위다.

## 돌다 만 것 · 실패한 것

- **[6] HANDOFF.md 개정은 불가능했다.** 원본이 작업트리·git 이력·디스크·백업 zip
  어디에도 없다. 개정 대신 신규 작성했고 `BLOCKED.md` 에 근거를 남겼다.
  "기존 반전 3개", "열린작업 #6", "docs/06 §5.2" 처럼 원본을 봐야 쓸 수 있는
  지시는 이행하지 못했다.
- **캐시 해시 사고.** `Config.credit_loss` 를 추가하자 해시가 `cfg.__dict__` 전체를
  쓰는 탓에 기존 캐시가 전부 무효화됐다(W=8 의 72GB 포함). 나중에 추가된 필드는
  기본값일 때 해시에서 빼도록 고쳐 전량 복구했다. 그 사이 2/4 를 한 번 헛빌드했다.
- **|T|=4 W=7 (CSR 344GB), |T|=5 W=6 (218GB) 는 돌리지 않았다.** 디스크·시간상
  가능하긴 하나 [4] 의 질문(선별이 퍼지는가)에 답하는 데 필요하지 않았다.
- **W 모형에서의 표현가능 상한은 이번에도 재측정하지 않았다** (w2 에서 남긴 숙제).

