# W-정식화 본 분석 (w2) — DIGEST

생성 2026-08-20. 원자료: `results/w_model/W*.json`, `summary_w.csv`,
`loss_correction.csv`, `legacy_loss.md`.

---

## [0] 편향 방향 — 기존 g\* 는 **아래로** 편향이다 (w1 서술 정정)

w1 커밋(79de2d3)과 w1 TASK 배경은 무료 소실이 "g\* 를 위로 편향시킨다" 고 적었다.
**틀렸다.** 소실은 수익 0·비용 0 으로 사라지는 것이고 강제매각은 +p_rc×kWh 로
나가는 것인데, 둘 다 창고 자리를 먹지 않고 다음 상태도 같다. 전이커널이 동일하고
보상만 다르므로 누락된 것은 **비용이 아니라 수익**이다 → 기존 g\* 는 낮게 나온다.

독립인 두 경로가 1e-7 이내로 일치한다 — (1) 정상분포 항등식 g = d·r 에서 d·Δr,
(2) 정책행 `rsa` 에 Δr 을 더한 보상수정 정책평가.

| 버퍼 | 기존 g\* | 소실가치 | 보정 g\* | 상승 |
|---|---:|---:|---:|---:|
| NMAX=2, SMAX=2 | 3,993,824 | 150,165 | 4,143,988 | +3.76% |
| NMAX=2, SMAX=3 | 4,101,817 | 150,165 | 4,251,981 | +3.66% |
| NMAX=2, SMAX=4 | 4,160,186 | 150,165 | 4,310,350 | +3.61% |
| NMAX=3, SMAX=2 | 4,233,194 | 45,916 | 4,279,110 | +1.08% |
| NMAX=3, SMAX=3 | 4,344,695 | 21,362 | 4,366,057 | +0.49% |

단서. 기존 최적정책을 고정한 채 보상만 고친 값이라 W-모형 g\* 자체는 아니다.
확정되는 것은 편향의 **방향**과 그 **하한**이다.

## [1] 정확해 가능 경계

|S| = C(W+12,12) 이다. 아래는 **실측** (추정이 아니다).

| W | \|S\| | n_sa | nnz | CSR | 경로 | 빌드 | 해 | PI |
|---:|---:|---:|---:|---:|---|---:|---:|---:|
| 4 | 1,820 | 30,089 | 2,534,035 | 0.0GB | in-RAM | 1s | 0s | 69 |
| 5 | 6,188 | 191,720 | 20,856,430 | 0.3GB | in-RAM | 5s | 0s | 109 |
| 6 | 18,564 | 1,060,850 | 151,069,345 | 1.8GB | in-RAM | 29s | 0s | 149 |
| 7 | 50,388 | 5,245,160 | 990,883,180 | 11.9GB | 스트리밍 | 134s | 44s | 7 |
| 8 | 125,970 | 23,652,230 | 6,007,752,520 | 72.1GB | 스트리밍 | 1002s | 644s | 7 |

경계 밖 (표본추정, 60상태)

| W | \|S\| | nA 추정 | nnz 추정 | CSR 추정 |
|---:|---:|---:|---:|---:|
| 9 | 293,930 | 96,448,231 | 142,681,460,133 | 1,712GB |
| 10 | 646,646 | 400,360,093 | 279,376,560,630 | 3,353GB |

**이 하드웨어에서 정확해가 가능한 최대는 W=8 이다.** 근거는 실측이다.

- W=8 은 실제로 끝까지 풀었다 — CSR 72.1GB, 빌드 1,002초, 해 644초(PI 7회).
  빌드 중 MemAvailable 최저는 48GB 로 62GB 시스템에 여유가 있었다.
- W=9 는 CSR 추정 1,712GB 다. 표본추정이 실측 대비 과대평가하는 경향을 감안해도
  (W=8 은 105.7GB 추정 → 72.1GB 실측, 1.47배 과대) 실제 1,160GB 급이고,
  NVMe 여유 공간 631GB 를 두 배 가까이 넘는다. 디스크에서 먼저 막힌다.
- 시간으로도 막힌다. W=7→8 에서 nnz 6.1배에 빌드 7.5배(134초→1,002초)였다.
  같은 비율이면 W=9 빌드는 4시간 안팎이고 PI 한 회의 전량 스윕만 1TB 이상 읽는다.

기존 칸의 유효 총량 대응(2/2→8, 2/3→9, 2/4→10, 3/2→11, 3/3→12)으로 보면,
**W-정식화에서 정확해로 닿을 수 있는 것은 가장 작은 칸(2/2) 하나뿐**이다.
용량을 하나로 묶으면 상태공간이 C(W+12,12) 로 커져 기존 정식화보다 훨씬 빨리 터진다
(2/2 는 1,485 상태인데 같은 총량의 W=8 은 125,970 상태 — 85배).

## [2] 기존 모형 vs W 모형

### g\*(W) 와 한계가치

| W | g\*(W) | Δg\*/ΔW | 대응 기존 칸 | 기존 g\* | 기존 보정 g\* |
|---:|---:|---:|---|---:|---:|
| 4 | 4,283,759 | — | — | — | — |
| 5 | 4,375,450 | 91,691 | — | — | — |
| 6 | 4,434,439 | 58,989 | — | — | — |
| 7 | 4,470,330 | 35,891 | — | — | — |
| 8 | 4,493,099 | 22,770 | NMAX=2, SMAX=2 | 3,993,824 | 4,143,988 |

### 벤치마크 갭 (%)

| W | B1 | B2 | INDEX | B_fast | B_fast thr |
|---:|---:|---:|---:|---:|---:|
| 4 | 69.486 | 25.393 | 20.242 | **14.134** | 0 |
| 5 | 70.126 | 26.957 | 21.977 | **14.087** | 0 |
| 6 | 70.523 | 27.928 | 23.083 | **14.720** | 0 |
| 7 | 70.760 | 28.507 | 23.767 | **15.333** | 0 |
| 8 | 70.908 | 28.869 | 24.220 | **15.762** | 0 |

### 강제매각 (정상분포 가중, 기간당)

| W | 최적: 대수 | 가치 | 발동확률 | B_fast: 대수 | 가치 |
|---:|---:|---:|---:|---:|---:|
| 4 | 1.2221 | 310,797 | 71.40% | 1.2508 | 314,541 |
| 5 | 0.8514 | 205,136 | 55.32% | 0.6972 | 158,998 |
| 6 | 0.6549 | 152,007 | 45.55% | 0.2712 | 56,450 |
| 7 | 0.5022 | 113,491 | 36.93% | 0.0516 | 9,911 |
| 8 | 0.3187 | 70,000 | 25.23% | 0.0000 | 0 |

### 최적정책 구조 — 차종별 행동 (정상분포 가중, 기간당 대수)

**W=4**

| 차종 | 매각 | 신속 | 정밀직행 | 보유 | 선별매각 | 선별정밀 | 선별보유 |
|---|---:|---:|---:|---:|---:|---:|---:|
| 레이 | 0.2621 | 0.0000 | 0.0000 | 0.0000 | 0.0000 | 0.0000 | 0.0000 |
| 코나 | 0.0000 | 1.2957 | 0.1439 | 0.0000 | 0.1013 | 0.8371 | 0.6004 |
| SM3 | 0.6763 | 0.0000 | 0.0000 | 0.0000 | 0.0000 | 0.0000 | 0.0000 |

**W=5**

| 차종 | 매각 | 신속 | 정밀직행 | 보유 | 선별매각 | 선별정밀 | 선별보유 |
|---|---:|---:|---:|---:|---:|---:|---:|
| 레이 | 0.3827 | 0.0000 | 0.0000 | 0.0000 | 0.0000 | 0.0000 | 0.0000 |
| 코나 | 0.0000 | 1.4333 | 0.0999 | 0.0000 | 0.1512 | 0.8868 | 0.9526 |
| SM3 | 0.8326 | 0.0000 | 0.0000 | 0.0000 | 0.0000 | 0.0000 | 0.0000 |

**W=6**

| 차종 | 매각 | 신속 | 정밀직행 | 보유 | 선별매각 | 선별정밀 | 선별보유 |
|---|---:|---:|---:|---:|---:|---:|---:|
| 레이 | 0.4539 | 0.0000 | 0.0000 | 0.0000 | 0.0000 | 0.0000 | 0.0000 |
| 코나 | 0.0000 | 1.5122 | 0.0637 | 0.0000 | 0.1674 | 0.9278 | 1.4906 |
| SM3 | 0.8828 | 0.0324 | 0.0000 | 0.0000 | 0.0224 | 0.0040 | 0.0304 |

**W=7**

| 차종 | 매각 | 신속 | 정밀직행 | 보유 | 선별매각 | 선별정밀 | 선별보유 |
|---|---:|---:|---:|---:|---:|---:|---:|
| 레이 | 0.5154 | 0.0000 | 0.0000 | 0.0000 | 0.0000 | 0.0000 | 0.0000 |
| 코나 | 0.0000 | 1.5613 | 0.0411 | 0.0000 | 0.1773 | 0.9534 | 2.0879 |
| SM3 | 0.9572 | 0.0228 | 0.0000 | 0.0000 | 0.0160 | 0.0026 | 0.0254 |

**W=8**

| 차종 | 매각 | 신속 | 정밀직행 | 보유 | 선별매각 | 선별정밀 | 선별보유 |
|---|---:|---:|---:|---:|---:|---:|---:|
| 레이 | 0.5968 | 0.0000 | 0.0000 | 0.0000 | 0.0000 | 0.0000 | 0.0000 |
| 코나 | 0.0000 | 1.5977 | 0.0300 | 0.0000 | 0.1911 | 0.9661 | 2.5678 |
| SM3 | 1.0405 | 0.0163 | 0.0000 | 0.0000 | 0.0113 | 0.0019 | 0.0252 |

### (a) g\* 차이는 소실가치와 정합적인가

대응쌍 W=8 ↔ NMAX=2/SMAX=2 (둘 다 유효 총량 8). W 모형이 4,493,099, 기존이 3,993,824 로 **499,275 높다**.
이 중 소실보정분이 150,165 로 30% 를 설명하고, 나머지 349,111(70%)는 **용량 풀링**에서 온다.

풀링이 왜 큰가. 기존 2/2 는 차종별 상한 2 가 셋 + 선별완료 상한 2 로 쪼개져 있어
코나만 4대 들고 있는 상태를 아예 표현하지 못한다. W=8 은 같은 총량을 하나로 묶어
필요한 차종에 몰아 쓸 수 있다. 즉 g\* 차이의 방향은 [0] 의 예측과 맞고,
크기는 소실보정만으로는 설명되지 않는다 — 정식화 교체가 소실 수정 이상의 일을 한다.

### (b) B_fast 갭

기존 5칸에서 10.502~14.102% 였다. W 모형에서는 14.087~15.762% 이고
대응쌍(W=8 ↔ 2/2)에서 **15.762% vs 10.502%** 로 커졌다.
방향은 유지된다 — B_fast 는 여전히 네 벤치마크 중 가장 좋고 최적과는 뚜렷이 멀다.

갭이 커진 이유는 최적정책 쪽이 좋아졌기 때문이다. 창고가 하나로 묶이면 최적은
선별완료품을 **들고 기다리는** 여지를 갖는다(아래 구조표에서 선별보유가 W 와 함께
0.60 → 2.57 로 증가). B_fast 는 정의상 전량 신속검사 후 상위 CAP 만 정밀이고
나머지를 즉시 매각하므로 그 여지를 못 쓴다. W=8 에서 B_fast 의 강제매각이
0.0000대인 것이 방증이다 — 재고를 쌓지 않으니 창고가 찰 일이 없다.

### (c) 최적정책 구조 — 유지되지만 무게중심이 옮겨간다

**유지된다.** 레이(R1)는 전 구간에서 100% 무검사 즉시매각이고, SM3 도 대부분
즉시매각이다(W≥6 에서 0.02~0.03대만 신속검사로 샌다). 검사는 코나에 집중된다.
"저가치 무검사 / 중간만 선별" 이라는 양끝 생략 구조는 그대로다.

**달라진 것.** W 가 커질수록 코나의 **정밀직행이 줄고**(0.1439 → 0.0300)
**선별보유가 는다**(0.6004 → 2.5678). 자리가 넉넉해지면 희소한 정밀검사 용량을
미리 확정해 쓰기보다, 신속검사로 신호를 받아 두고 좋은 신호가 나올 때까지
**기다리는** 쪽이 낫기 때문이다. 자리 경합이 완화되며 나타나는 전형적인 전환이다.

강제매각도 같은 방향이다 — 최적정책 하 발동확률이 W=4 의 71.40% 에서
W=8 의 25.23% 로 떨어진다. 정책이 "미리 팔아 자리를 비우는" 회피를 덜 해도 된다.

## [3] 오염된 기존 결과의 정정

### 가법분해 재검정

- **원본** — SMAX 2→3: NMAX=2 에서 107,993 / NMAX=3 에서 111,501. NMAX 2→3: SMAX=2 에서 239,370 / SMAX=3 에서 242,879. NMAX/SMAX 비 **2.22배**, 교호작용 3,509 (g\* 대비 0.081%)
- **소실보정** — SMAX 2→3: NMAX=2 에서 107,993 / NMAX=3 에서 86,947. NMAX 2→3: SMAX=2 에서 135,121 / SMAX=3 에서 114,076. NMAX/SMAX 비 **1.25배**, 교호작용 -21,046 (g\* 대비 0.482%)

보정 후 NMAX 우위가 2.22배 → 1.25배로 줄고, 가법 잔차가 0.081% → 0.482% 로
**6배 커지며 부호가 뒤집힌다**. v5b 의 "NMAX 효과가 SMAX 의 2.2배 / 가법분해가
성립한다" 는 상당 부분 무료 소실의 인공물이다. NMAX 2→3 증분 239,370 중
104,249(43.6%)이 소실 감소분이기 때문이다.

반면 **SMAX 효과는 보정에 전혀 움직이지 않는다** (2→3 이 107,993, 3→4 가 58,369,
체감비 0.540 로 동일). 소실가치가 NMAX 와 도착과정만의 함수이고 SMAX 와 무관해서다.
SMAX 의 체감수확 결론은 그대로 유지된다.

### 갭은 오염에 무관한가 — 검정 결과 "대체로 그렇다, 그러나 정확히는 아니다"

갭 = (g\* − g_π)/g\* 이고 **소실가치는 정책마다 다르므로** 무관성은 가정이 아니라
검정 대상이다. 정책별 소실가치를 실측해 보정 갭을 다시 계산했다
(`gap_contamination_*.json`, `dcl_contamination_*.json`).

| 칸 | 정책 | 갭 원본 | 갭 보정 | 차이 |
|---|---|---:|---:|---:|
| N2S2 | B2 | 23.737% | 22.877% | -0.860%p |
| N2S2 | INDEX | 20.288% | 19.553% | -0.735%p |
| N2S2 | B_fast | 10.502% | 10.122% | -0.381%p |
| N2S3 | B2 | 25.745% | 24.836% | -0.909%p |
| N2S3 | INDEX | 22.434% | 21.642% | -0.792%p |
| N2S3 | B_fast | 12.878% | 12.423% | -0.455%p |
| N3S2 | B2 | 24.939% | 25.312% | +0.373%p |
| N3S2 | INDEX | 21.546% | 21.956% | +0.410%p |
| N3S2 | B_fast | 11.378% | 11.897% | +0.519%p |
| N3S2 | DCL(carry) | 0.131% | 0.140% | +0.009%p |
| N3S2 | DCL(legacy) | 2.926% | 3.053% | +0.127%p |

읽는 법. NMAX=2 칸에서는 모든 정책이 매 기간 미검사 재고를 비워 소실가치가
정책과 무관하게 같다 → 보정은 분모에만 걸려 갭이 일률적으로 **작아진다**.
NMAX=3 칸에서는 최적정책이 재고를 더 들고 있어 소실이 더 크고, 그래서 보정 갭이
오히려 **커진다**. 즉 부호조차 칸마다 다르다.

중요한 것은 크기다. **정책이 최적에 가까울수록 오염이 작다** — 최적과 소실가치가
비슷해져 분자에서 상쇄되기 때문이다. 3/2 에서 legacy DCL 은 +0.127%p 움직이는데
carry DCL 은 +0.009%p 뿐이다. 벤치마크처럼 최적에서 먼 정책일수록 최대 ±0.5%p 이동한다.

### v5b·v5c 결론 — 철회 / 유지

**철회한다**

1. "NMAX 효과가 SMAX 효과의 2.2배" → 소실보정 후 1.25배. 증분의 43.6%가 인공물.
2. "가법분해가 성립한다 (잔차 0.081%)" → 보정 후 0.482%, 부호 반전. 가법성 자체가 인공물.
3. g\* 의 **절대 수준**을 인용한 모든 진술. 5칸 전부 0.49~3.76% 아래로 편향.
4. w1 커밋의 "위로 편향" 서술 ([0] 참조).

**유지된다**

1. SMAX 체감수확 (2→3 이 3→4 의 1.85배). 보정에 전혀 안 움직인다.
2. 표현력 감사 — 레거시 디코더 상한 59.2%(3/2)~88.0%(2/4). 최적정책 라벨의
   **조합적 성질**이라 보상 오염과 무관하다. 소실을 보정해도 최적정책이 바뀌지
   않으므로(보상 상수 이동이 아니라 상태별 이동이지만 정책은 동일하게 유지된다)
   라벨도 그대로다.
3. 자기회귀 디코더의 우위. 3/2 에서 보정 후에도 legacy 3.053% vs carry 0.140%,
   비율 22배로 사실상 그대로 (원본 22.3배).
4. "사전등록 기준 ≤1% 가 carry 로 5/5 칸 통과" — 보정은 갭을 최대 +0.01%p 움직일
   뿐이라 결론이 안 바뀐다.
5. 시드 분산이 칸 간 차이보다 작다는 결론 (0.17~0.24%p vs 2.33%p).
6. 스트리밍 빌드·솔버의 성능 실측치.

**정정이 필요하다** — "방법론 결론은 오염과 무관" 이라는 표현은 엄밀하게는 틀렸다.
갭 수치 자체는 최대 ±0.5%p 움직인다. 다만 그 이동이 결론을 뒤집을 만큼 크지 않고,
최적에 가까운 정책일수록 이동이 작다는 것이 실측 결과다.

## [4] W 모형에서의 디코더 재확인

W=4~6 에서 시드 3개씩. 정확해는 같은 인스턴스를 다시 풀어 갭의 분모로 썼다.

| W | legacy (시드 3개) | 평균±SD | carry (시드 3개) | 평균±SD |
|---:|---|---:|---|---:|
| 4 | 2.412 / 4.641 / 1.661 | **2.905±1.266** | 0.007 / -0.000 / 0.016 | **0.008±0.006** |
| 5 | 1.894 / 1.830 / 1.515 | **1.747±0.166** | 0.001 / 0.004 / 0.001 | **0.002±0.001** |
| 6 | 3.088 / 48.616 / 1.783 | **17.829±21.776** | 0.028 / 0.000 / 0.000 | **0.009±0.013** |
| 7 | — | **—** | 0.000 | **0.000±0.000** |

**결론은 바뀌지 않는다 — 오히려 강해진다.** carry 는 세 W 모두 평균 0.01% 이하로
최적정책을 수치오차 내에서 재현한다. legacy 는 1.5~48.6% 로 흩어지고 W=6 시드1 은
48.6% 로 학습이 통째로 실패했다.

W 모형에서 격차가 더 벌어지는 이유는 구조적이다. 기존 정식화에서 미검사 슬롯 폭은
NMAX×3 (최대 9) 이었지만 W 모형에서는 W 자체다. 같은 특징을 가진 슬롯이 더 길게
늘어서고, legacy 디코더는 그 런을 쪼갤 수 없다(v5c §4.2). 즉 W-정식화는 레거시
디코더의 약점을 정확히 더 세게 누른다.

## 돌다 만 것 · 실패한 것

- **w1 의 야간 C 단계는 실행되지 않았다.** 8/19 밤 세션이 A 단계 보고 직후 끊겼고
  B·C 단계와 그때 약속한 `DIGEST.md` 는 만들어지지 않았다. 아침에 DIGEST 가 없던
  것은 그 때문이다. 이 문서는 w2 지시로 새로 만든 것이다.
- **W=9 이상은 시도하지 않았다.** 위 근거로 디스크에서 막히는 것이 명백해 빌드를
  걸지 않았다. 추정만 있고 실측은 없다.
- **[4] 는 W=4~6 만 했다.** W=7·8 의 DCL 은 돌리지 않았다. TASK 우선순위상 낮고,
  W=8 은 정확해 한 번에 27분이 든다.
- **표현가능 상한은 W 모형에서 재측정하지 않았다.** [4] 의 갭 결과가 결론을 이미
  가르므로(캐리 0.01% vs 레거시 최대 48.6%) 생략했다. v5c 의 측정 방법은 그대로
  적용 가능하다.
- 회귀 테스트 중 `test_stream_parity[2-3]` 이 한 번 OOM 으로 떨어진 적이 있다
  (같은 GPU 에서 다른 잡이 14.7GB 점유). 단독 재실행 통과. 코드 회귀가 아니다.

