# w5 — 유형 재정의(차종×용량) · 가격함수 직접회귀 · 재산출

생성 2026-08-20. w4 DIGEST(`../w4/DIGEST_w4.md`)의 후속. 각 절 끝에 **논문 문장**을 붙였다.
근거 문서는 `DATA_정합성_정리_20260820.md`(이하 «정합성 메모»)이고,
수치 출처는 `summary_w5.csv`, `policy_structure_w5.csv`, `W{4·5·6}.json`,
`data/types_w5.json` 이다. 실증 검증은 `validation.md` 에 따로 있다.

**한 줄 요약** — 유형을 `차종`에서 `차종×용량`으로 쪼개고 가격을 실거래 직접회귀로
바꾸자, w2 이래 문제였던 «선별이 한 차종에 몰린다»가 **풀렸다**. 신속검사가 세 유형에
나뉘고(최대 집중 99% → 60%), 실측 R1 유형은 모형이 스스로
전량 즉시매각한다.
대신 w3 이 세운 «즉시처분 강제의 비용»은 **부호가 뒤집혔다** — 정리가 아니라
그 인스턴스의 성질이었음이 드러났다.

---

## [0] 정합성 메모를 원자료로 먼저 검산했다

메모의 수치를 그대로 코드에 옮기기 전에, 원자료(재사용 273건 / 재활용 172건)에서
독립적으로 다시 계산했다. **핵심 수치는 전부 재현된다.**

| 메모 | 주장 | 재현 | |
|---|---|---|:--:|
| §1 | 배율 전기간 3.20 / 2023~ 3.44 / 2024~ 4.72 / 최근12M 4.50 | 동일 | ✓ |
| §1 | 연도별 배율 2.33 → 3.42 → 3.67 → 3.94 | 동일 | ✓ |
| §2.1 | 낙찰배수~SOH 의 R²=0.0008 | 0.0009 (2024~) | ✓ |
| §2.3 | 재활용 용량지수 월FE 1.187 (t=24.8) / 미통제 1.422 | 1.1872 (t=24.79) / 1.4216 | ✓ |
| §3 | 재사용 회귀 7.3157·1.7341·2.6000·0.2953, σ=0.5012, R²=0.770 | 소수 4자리까지 동일 | ✓ |
| §3 | 재활용 회귀 7.2159·1.2675·0.5012, σ=0.5166, R²=0.827 | 소수 4자리까지 동일 | ✓ |
| §3 | 리튬 기준 35.84 (42개월), 기하평균 27.49, 범위 8.16~70.42 | 35.8357 / 27.4915 / 동일 | ✓ |
| §4.1 | 레이 병합 시 n=60, q_P=0.217 | 동일 | ✓ |
| §5 | 유형별 실측 손익배수 11종 | 레이 제외 전부 동일 | ✓ |
| §5 | 켄달 타우 +0.782 | 메모 열로는 +0.782, 재계산 열로는 +0.745 | ~ |
| §2.1 | ln(참가자수) 계수 +0.284, R²=0.074 (2024~ 로 서술) | **전기간** 값이다 | ✗ |

마지막 줄이 유일한 실질 불일치다. 메모 §2.1 은 SOH 회귀와 참가자수 회귀를 모두
«2024-01 이후» 절에 넣었는데, 참가자수 쪽 수치(+0.284, R²=0.0736, 2명 1.83배 →
9명 2.81배)는 **전기간 273건**에서 나온다. 2024~ 94건으로 좁히면 +0.271, R²=0.052 다.
부호·크기·유의성이 모두 같은 방향이라 «낙찰배수를 움직이는 것은 참가자 수»라는
결론은 그대로지만, 논문에 옮길 때는 창을 바로잡아야 한다.

§5 의 레이_16.4 는 메모가 0.00, 여기서는 **0.14** 다. 메모 §5 표가 §4.1 의 용량
병합 **이전** 값(q_P=0)을 담고 있어서다. 병합 후 q_P=0.217 이 맞고, 메모 §4.1 이
스스로 그렇게 적고 있다 — 표를 다시 내지 않았을 뿐이다.

> **논문 문장** — "낙찰배수는 SOH 를 설명하지 못하고(R²<0.001), 실제 설명변수는
> 입찰참가자 수다(전기간 ln 계수 +0.284, R²=0.074). 이는 모형 외생이므로
> 낙찰배수를 상수로 두고 로그정규 잡음의 평균만 맞춘다."

## [1] 유형 재정의 — `차종` 이 아니라 `차종 × 용량`

같은 차종이라도 용량이 다르면 다른 배터리다. w4 까지는 차종으로만 묶어 서로 다른
팩을 한 유형으로 취급했다. 복수 용량이 실재하는 차종은 쏘울(27/30/64)·SM3(26.6/35.9)·
아이오닉(28/38.3)·코나(39.2/64/66)·볼트(60/66)·레이(16/16.4/35.2)·모델3(50/72) 이고,
웹 검증 결과 전부 **실제 사양 차이**다.

### 표기 오류 하나를 함께 잡았다

`pool.csv` 에서 레이가 두 유형으로 갈리는데 통과확률이 **0 과 1 로 완벽히 분리**됐다
— 레이_16.0 은 n=13 전부 재사용, 레이_16.4 는 n=47 전부 재활용. 확률이 0/1 로
갈리는 것은 통계가 아니라 **재사용 파일은 16.0, 재활용 파일은 16.4 로 적었다**는
표기 규칙 차이다. 병합하면 n=60, q_P=0.217 로 정상값이 된다.

`normalize_cap()` 이 이 규칙을 구현한다 — 같은 차종의 두 용량 표기가 3% 이내로
근접하고, q_P 가 각각 정확히 0 과 1 이며, 양쪽 표본이 5건 이상일 때만 병합한다.
세 조건을 모두 걸어야 실제 사양 차이를 잘못 뭉개지 않는다. **pool.csv 전체에서
걸리는 쌍은 레이 하나뿐이다.**

> **정합성 메모와 다른 점.** 메모 §4.1 은 볼트_66.0·코나_39.2·아이오닉_38.3 도
> "같은 패턴"으로 묶었으나 셋 다 실재 사양이고 용량 차이가 10~129% 라 표기 오류로
> 볼 수 없다. 66kWh 팩을 60kWh 유형에 합치면 용량 자체가 오염된다. 이들은 병합이
> 아니라 표본수 하한(pool≥10)에서 걸러지고, 결과는 메모 §5 표와 같다.

> **논문 문장** — "차종만으로 묶으면 서로 다른 사양의 팩이 한 유형에 섞인다.
> 차종×용량으로 쪼개면 SM3 는 26.6kWh(손익배수 0.02)와 35.9kWh(1.27)로 갈리는데,
> 이 둘은 정밀검사 손익분기의 반대편에 있다."

## [2] 가격함수 — 2층 구조를 폐기하고 실거래 낙찰가를 직접 회귀한다

w4 에서 낙찰배수의 SOH 계수가 0 이 되면서(R²=0.0008) 낙찰배수는 상수 잡음일 뿐이
됐고, 층을 나눌 의미가 사라졌다. 예정가격을 거치지 않고 낙찰가를 바로 회귀한다.

```
ln P_reuse   = 7.3157 + 1.7341·ln(cap) + 2.6000·ln(s) + 0.2953·ln(P_Li) + ε   σ=0.5012  R²=0.770  n=273
ln V_recycle = 7.2159 + 1.2675·ln(cap)              + 0.5012·ln(P_Li) + η   σ=0.5166  R²=0.827  n=172
```

바뀐 것 셋.

1. **시점 효과를 리튬으로 설명한다.** 재활용가가 3~6배 변동한 것은 없앨 노이즈가
   아니라 설명할 신호다. 월 더미 대신 리튬을 넣으면 재활용 R² 가 0.742(용량만) →
   0.827 로, 월FE 상한 0.916 과의 격차를 절반가량 메운다. 코발트는 넣지 않는다
   — 계수가 음수로 나와 경제적 의미가 없고 27개 시점의 다중공선성이 만든 인공물이다.
   리튬은 자료기간 시점평균 **35.84** 에 고정한다 (정상상태 분석).
2. **재활용가치가 용량에 선형이 아니다.** 구 판의 `p_rc × cap` 은 지수를 1.0 으로
   못박은 것인데 실측 지수는 월FE 통제하에 **1.2675**(t=24.8, R²=0.916) 다.
   pooled `p_rc` 는 대용량 팩의 회수가치를 과소평가한다.
3. **로그정규 보정을 명시했다.** 회귀가 ln 스케일이라 exp(Xβ) 는 중앙값이지
   기댓값이 아니다. MDP 는 기대보상을 최대화하므로 E[P]=exp(Xβ+σ²/2) 를 써야 한다.
   표본평균 대조로 확인했다 — 보정판의 예측평균/실측평균이 재사용 1.023 · 재활용
   0.977 인 반면, 미보정판은 0.902 · 0.855 로 10~15% 과소다 (`validation.md` §1).

한계는 그대로 남는다: 원리적으로 회수가치를 정하는 것은 화학조성이지만 한국
시장에서 조성과 용량이 거의 같은 변수라(LFP 용량중앙 16kWh, NCM 59.4kWh) 둘을
함께 넣으면 NCM 더미가 유의성을 잃고 부호가 뒤집힌다 — **식별 불가**. 용량을
대리변수로 쓰고 한계에 명시한다.

> **논문 문장** — "재활용 회수가치는 용량에 선형이 아니다(지수 1.27). 폐배터리
> 가격의 시점 변동은 리튬 시세로 상당 부분 설명되며, 리튬 탄력성이 재활용(0.501)이
> 재사용(0.295)보다 크므로 리튬 강세기에는 두 채널의 격차가 좁아져 선별 유인이 준다."

## [3] 유형 재선정 — 아이오닉_28.0 · 코나_64.0 · 볼트_60.0 · 포터2_58.8

손익배수의 정의를 정합성 메모 §4.2 대로 고쳤다. 정밀검사는 통과확률 q_P 로만
재사용 매출을 얻으므로 q_P 는 **분자에 유형별로** 들어가야 한다.

```
w4 :  r = (E[재사용] − V^S) / (C_p / q̄_P)      q̄_P = 0.5135 로 고정
w5 :  r = q_P · (E[재사용] − V^S) / C_p         유형별 q_P
```

E·V^S 는 **모형을 전혀 쓰지 않은** 실거래 팩당 중앙값(전기간)이다.

| 유형 | pool | q_P | 용량 | μ(SOH) | 재사용/재활용 | 실측 손익배수 | 등급 |
|---|---:|---:|---:|---:|---|---:|:--:|
| SM3_26.6 | 75 | 0.72 | 26.6 | 0.680 | 23/8 | **0.02** | R1 |
| 쏘울_27.0 | 16 | 0.19 | 27.0 | 0.850 | 4/9 | **0.03** | R1 |
| 레이_16.4 | 60 | 0.22 | 16.4 | 0.777 | 7/19 | **0.14** | R1 |
| 아이오닉_28.0 **★** | 68 | 0.79 | 28.0 | 0.853 | 47/9 | **0.63** | R1 |
| SM3_35.9 | 18 | 0.94 | 35.9 | 0.932 | 11/4 | **1.27** | R3 |
| 코나_64.0 **★** | 130 | 0.65 | 64.0 | 0.877 | 69/22 | **1.42** | R3 |
| 볼트_60.0 **★** | 86 | 0.83 | 60.0 | 0.935 | 47/12 | **3.53** | R2 |
| 니로_64.0 | 44 | 0.77 | 64.0 | 0.879 | 30/6 | **3.54** | R2 |
| 쏘울_64.0 | 13 | 0.77 | 64.0 | 0.868 | 8/4 | **5.49** | R2 |
| 포터2_58.8 **★** | 21 | 0.71 | 58.8 | 0.946 | 18/13 | **5.91** | R2 |
| 봉고3_58.8 | 10 | 0.70 | 58.8 | 0.949 | 6/3 | **11.03** | R2 |

★ 넷이 확정 인스턴스다. 손익분기 1.0 을 사이에 두고 **R1 하나 · R3 하나 · R2 둘**이
놓이는 촘촘한 사다리이고, pool 표본이 68/130/86/21 이라 6개 특징을 전부 실측으로
채운다(기본값 대체 없음).

w4 인스턴스(SM3·쏘울·볼트·코나)와 겹치지 않는 이유는 두 가지가 동시에 바뀌어서다.
유형을 용량으로 쪼개면서 SM3 가 26.6(0.02)과 35.9(1.27)로 갈렸고, 손익배수에
유형별 q_P 를 넣으면서 서열 자체가 재배열됐다.

> **논문 문장** — "정밀검사의 손익배수는 유형별 통과확률에 비례한다. 통과확률을
> 전체 평균으로 고정하면 통과확률이 낮은 유형의 검사가치가 과대평가된다."

## [4] 재산출 — 정확해와 벤치마크

|T|=4, 상태공간 C(W+16,16). NARR=4, λ=0.9, C_p=50만, C_f=2만, M_cyc=1 (CAP=1).

| W | 상태수 | (s,a) | nnz | CSR GB | g* | Δg* | B1 갭 | B2 갭 | INDEX 갭 | B_fast 갭 | B_fast_hold 갭 |
|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|
| 4 | 4,845 | 201,000 | 39,270,210 | 0.5 | 8,045,931 | — | 32.730% | 7.734% | 13.606% | 4.902% | 5.269% |
| 5 | 20,349 | 1,912,352 | 500,560,760 | 6.0 | 8,189,573 | 143,642 | 33.909% | 9.352% | 15.157% | 4.010% | 6.927% |
| 6 | 74,613 | 15,496,916 | 5,484,756,410 | 65.8 | 8,280,433 | 90,860 | 34.635% | 10.347% | 16.125% | 3.661% | 7.983% |

**한계가치는 체감한다** — Δg* 가 143,642 → 90,860 로 줄어든다. w3·w4 와 같은 방향이다.

### 분해가 뒤집혔다 — w3 결론의 정정

w3 [2] 는 관행의 손실을 두 갈래로 갈랐다.

```
gap(B_fast) = gap(B_fast_hold) + [gap(B_fast) − gap(B_fast_hold)]
            = [전량검사 강제의 비용] + [즉시처분 강제의 비용]
```

w5 에서는 둘째 항이 **음수**다.

| W | B_fast 갭 | B_fast_hold 갭 | 전량검사 강제 | 즉시처분 강제 |
|---:|---:|---:|---:|---:|
| 4 | 4.902% | 5.269% | 5.269%p | **-0.367%p** |
| 5 | 4.010% | 6.927% | 6.927%p | **-2.917%p** |
| 6 | 3.661% | 7.983% | 7.983%p | **-4.322%p** |

원인은 `B_fast_hold` 가 `B_fast` 의 **완화가 아니라 다른 고정정책**이라는 데 있다.
둘 다 전량 신속검사를 강제하고, 선별완료품 처리만 다르다 — B_fast 는 정밀 CAP건
외 전부 즉시매각, B_fast_hold 는 강제분(V^PS ≤ V^S)만 팔고 나머지는 **보유**다.
보유는 선택지가 아니라 의무이므로, 창고가 좁고 유형이 전부 값비싼 w5 인스턴스에서는
보유가 자리를 먹어 도착 시 강제매각을 늘린다. 즉 즉시처분 강제는 비용이 아니라
**이득**이다. w3·w4 에서 양수였던 것은 정리가 아니라 그 인스턴스의 성질이었다.
(`tests/test_w5.py::test_bfast_hold_is_not_a_relaxation` 이 이 부호를 못박는다.)

> **논문 문장** — "관행 정책의 손실을 「전량검사 강제」와 「즉시처분 강제」로
> 가법 분해할 때, 둘째 항의 부호는 인스턴스에 의존한다. 창고가 좁고 유형이 고르게
> 값비싸면 즉시처분은 비용이 아니라 자리를 비우는 이득이 된다."

### 강제매각

| W | 최적: 대수/기간 | 가치 | 발동확률 | B_fast: 대수/기간 | 가치 |
|---:|---:|---:|---:|---:|---:|
| 4 | 1.3655 | 1,700,122 | 80.48% | 1.3826 | 1,758,043 |
| 5 | 0.9560 | 1,151,856 | 62.88% | 0.8891 | 1,065,358 |
| 6 | 0.6247 | 723,292 | 45.96% | 0.4547 | 505,469 |

## [5] 정책 구조 — 선별은 퍼지는가, 몰리는가

**w2 의 미해결 문제였다.** 당시 신속검사의 99% 가 코나 하나에 몰렸고, 그것이 모형
결함인지 인스턴스 구성 탓인지 갈리지 않았다. 손익분기 양쪽에 유형이 고르게 놓인
지금 인스턴스에서 다시 물었다.

| W | 아이오닉_28.0 | 코나_64.0 | 볼트_60.0 | 포터2_58.8 | 최대 집중 |
|---:|---:|---:|---:|---:|---:|
| 4 | 0.0% | 69.6% | 25.6% | 4.8% | 69.6% |
| 5 | 0.0% | 63.8% | 30.0% | 6.2% | 63.8% |
| 6 | 0.0% | 59.9% | 33.0% | 7.2% | 59.9% |

(신속검사 총량 중 각 유형이 차지하는 비중. 도착 비중은 아이오닉 22.3% · 코나 42.6% ·
볼트 28.2% · 포터2 6.9% 다.)

**선별이 퍼진다.** 최대 집중이 99% 에서 60% 로 내려오고
신속검사가 세 유형에 나뉜다. 동시에 **아이오닉_28.0 은 신속·정밀 어느 쪽도 받지
못하고 전량 즉시매각된다**
— 실측 등급이 R1(손익배수 0.63)인 유형이다. 즉 모형은 가격자료의 손익배수를 보지
않고도 «검사할 가치가 없는 유형»을 스스로 골라낸다.

| W | 유형 | 매각 | 신속 | 정밀직행 | 선별후정밀 | 신속률 | 정밀률 |
|---:|---|---:|---:|---:|---:|---:|---:|
| 4 | 아이오닉_28.0 | 0.2133 | 0.0000 | 0.0000 | 0.0000 | 0.0% | 0.0% |
| 4 | 코나_64.0 | 0.0000 | 1.3129 | 0.0223 | 0.4966 | 98.3% | 38.9% |
| 4 | 볼트_60.0 | 0.0000 | 0.4838 | 0.1013 | 0.3174 | 82.7% | 71.6% |
| 4 | 포터2_58.8 | 0.0000 | 0.0907 | 0.0101 | 0.0517 | 90.0% | 61.3% |
| 5 | 아이오닉_28.0 | 0.3561 | 0.0000 | 0.0000 | 0.0000 | 0.0% | 0.0% |
| 5 | 코나_64.0 | 0.0000 | 1.4058 | 0.0107 | 0.4396 | 99.2% | 31.8% |
| 5 | 볼트_60.0 | 0.0000 | 0.6612 | 0.0669 | 0.4067 | 90.8% | 65.0% |
| 5 | 포터2_58.8 | 0.0000 | 0.1373 | 0.0060 | 0.0698 | 95.8% | 52.9% |
| 6 | 아이오닉_28.0 | 0.4850 | 0.0000 | 0.0000 | 0.0000 | 0.0% | 0.0% |
| 6 | 코나_64.0 | 0.0052 | 1.4672 | 0.0025 | 0.4237 | 99.5% | 28.9% |
| 6 | 볼트_60.0 | 0.0000 | 0.8073 | 0.0301 | 0.4633 | 96.4% | 58.9% |
| 6 | 포터2_58.8 | 0.0000 | 0.1754 | 0.0026 | 0.0778 | 98.6% | 45.1% |

> **논문 문장** — "손익분기 양쪽에 유형이 고르게 놓인 인스턴스에서 신속검사는 한
> 유형에 몰리지 않고 손익분기 위쪽 유형들에 나뉜다. 손익분기 아래 유형은 검사 없이
> 즉시 처분된다. w2 에서 관측된 «한 차종 집중»은 모형의 결함이 아니라 경계 유형이
> 없던 인스턴스 구성의 결과였다."

## [6] DCL — carry 디코더

| W | 시드수 | 평균 갭 | 표준편차 | 최대 |
|---:|---:|---:|---:|---:|
| 4 | 3 | 0.033% | 0.009% | 0.042% |
| 5 | 3 | 0.003% | 0.000% | 0.004% |
| 6 | 3 | 0.000% | 0.000% | 0.000% |

legacy 디코더는 v5c 에서 결론이 났으므로 돌리지 않았다.

## [7] 구 결과와의 대조 — 무엇이 바뀌고 무엇이 유지되는가

| 항목 | w4 (차종, 2층가격) | w5 (차종×용량, 직접회귀) | 판정 |
|---|---|---|---|
| 인스턴스 | SM3·쏘울·볼트·코나 | 아이오닉_28·코나_64·볼트_60·포터2_58.8 | 교체 |
| g*(W=4) | 3,854,564 | 8,045,931 | 2.1배 |
| B_fast 갭 (W=4) | 7.125% | 4.902% | 축소 |
| B_fast 갭 (W=5) | 6.695% | 4.010% | 축소 |
| B_fast 갭 (W=6) | 6.982% | 3.661% | 축소 |
| 가지치기(DUMP) | SM3·쏘울 R1 로 제거 | **없음** — 넷 다 살아남음 | 행동공간 4.8배 |
| 즉시처분 강제 비용 | 양수 | **음수** | 부호 반전 |
| 한계가치 체감 | 예 | 예 | 유지 |
| DCL 갭 1% 이내 | 예 | 예 | 유지 |
| 실측 등급 일치 | 4/4 (차종 4종) | 9/11 (전 11유형) | 정의가 달라 직접 비교 불가 |

마지막 줄은 **같은 것을 재는 지표가 아니다**. w4 의 4/4 는 차종 4종을
`r=(E−V^S)/(C_p/q̄_P)` 로 매긴 것이고, w5 의 9/11 는 전 11유형을
`r=q_P(E−V^S)/C_p` 로 매긴 것이다. 유형 수도 정의도 다르므로 «악화»로 읽으면 안 된다.
확정 인스턴스 4유형만 놓고 보면 §3.3 의 이분 판정이 4/4 로 일치한다.

**유지되는 것**: 한계가치 체감, 벤치마크 서열(B1 ≪ INDEX < B2 < B_fast < g*),
DCL 이 정확해를 1% 안에서 재현한다는 것.
**바뀐 것**: g* 의 수준(가격함수가 통째로 바뀌었으니 당연하다), 즉시처분 강제의
부호, 그리고 «선별이 한 유형에 몰린다»가 풀렸다는 것.


## [8] 돌다 만 것 · 실패한 것 · 하지 않은 것

### W=7 은 돌리지 못했다 — 디스크가 모자란다

먼저 nnz 를 표본추정했고(TASK 진행원칙), 추정기가 믿을 만한지 **w4 의 참값으로**
먼저 검산했다 — w4 W=7 추정 5,183,906,054 vs 실측 5,156,551,960 (+0.5%).

| W | 상태수 | nnz 추정 | CSR 추정 | 실측 nnz | 실측 CSR | 판정 |
|---:|---:|---:|---:|---:|---:|---|
| 4 | 4,845 | 45,977,435 | 0.6 GB | 39,270,210 | 0.5 GB | 완료 |
| 5 | 20,349 | 565,973,520 | 6.8 GB | 500,560,760 | 6.0 GB | 완료 |
| 6 | 74,613 | 6,060,577,716 | 72.7 GB | 5,484,756,410 | 65.8 GB | 완료 |
| 7 | 245,157 | 79,203,975,196 | 950.4 GB | — | — | 디스크 부족 |
| 8 | 735,471 | 290,101,816,678 | 3481.2 GB | — | — | 규모 불가 |

저장형식은 int32 인덱스 + float64 확률 = **정확히 12바이트/nnz** 다(실측 확인).
W=7 은 추정 950GB 이고, 관측된 증가율(nnz(W6)/nnz(W5)=11.0)로 외삽해도 **600GB 이상**이다.
작업 시점 여유 공간은 320GB 였고, 캐시에 이미 445GB(v5·w2~w4 재현용)가 들어 있다.
**기존 캐시를 지우면 공간은 나오지만 구 결과 재현이 깨지므로 지우지 않았다.**

w4 는 같은 |T|=4·W=7 을 61.9GB 로 풀었다. 차이는 가지치기다 — w4 는 SM3·쏘울이
모형 R1 이라 `DUMP` 로 잘려 나갔고, w5 는 모형 R1 이 하나도 없어 네 유형 모두
전 행동을 갖는다. (s,a) 쌍이 W=4 에서 65,964 → 201,000 으로 3.0배, nnz 는 4.1배다.

W=7 이 필요하면 선택지는 셋이다 — (a) 캐시 정리로 700GB 확보, (b) `/home/data`
(HDD, 1.7TB 여유)로 캐시 이전(느리다), (c) 확률을 float32 로 낮춰 8바이트/nnz 로
축소(정확도 검증 필요).

### 하지 않은 것

- **legacy 디코더 DCL**: v5c 에서 결론이 났으므로 carry 만 돌렸다(TASK 지시).
- **정합성 메모 §5 의 «모형 손익배수» 열 재현**: 이 구현으로는 정확히 나오지 않는다.
  메모가 어떤 SOH·보정 규약을 썼는지 적혀 있지 않다. 켄달 타우는 +0.782 vs +0.745 로
  결론은 같다. 이 문서의 값은 전부 이 저장소 코드가 낸 것이다.
- **쏘울_27.0 의 μ·σ**: SOH 표본이 3건뿐이라 `MIN_PASS=5` 하한에 걸려 기본값
  (0.85/0.06)으로 대체됐다. 메모 §5 는 3건 그대로 써서 0.813/0.151 로 적었다.
  확정 인스턴스에 없는 유형이라 결과에 영향은 없다.
- **연식(車齡)**: 메모 §6 의 음성 결과대로 넣지 않았다.

### 알려진 약점

- 재활용가의 유형 간 산포를 용량만으로 설명하지 못한다. 이것이 §3 의 등급 불일치
  둘(SM3_35.9·코나_64.0)의 직접 원인이다. `validation.md` §1.4 참조.
- 신규 입찰자료에 유찰이 없어 통과확률 q_P 는 구자료에서만 나온다. 두 자료의
  관측창이 다르다(2022.3~2025.3 vs 2022-01~2025-10).

