# w4 — 가격 재캘리브레이션 · 차종 재선정 · 재산출

생성 2026-08-20. w3 DIGEST(`../w_model/DIGEST_w3.md`)의 후속. 각 절 끝에 **논문 문장**을 붙였다.
수치 출처: `summary_w4.csv`, `policy_structure_w4.csv`, `validation_price.csv`, `W{4..7}.json`.
실증 검증은 `validation.md` 에 따로 있다.

**한 줄 요약** — 가격을 고치자 인스턴스의 경제 구조가 바뀌어 갭이 절반으로 줄었지만,
w3 이 세운 **정성적 결론 셋(분해 방향·한계가치 체감·DCL 1% 이내)은 모두 살아남았다.**
바뀐 것은 크기이고, 새로 얻은 것은 실증 정합성이다.

---

## [1] 새 파라미터 — 무엇이 얼마나 움직였나

`data/params.json` 을 교체하고 구 파일을 `data/params_v5.json` 으로 보존했다.

| 항목 | v5 | w4 | 뜻 |
|---|---:|---:|---|
| `g_c0` | 8.2569 | 6.1834 | 헤도닉 절편 ↓ |
| `g_cap` | 1.5815 | 1.9936 | 용량 탄력성 ↑ (초선형) |
| `g_s` | 2.8545 | 1.8912 | SOH 탄력성 ↓ |
| `M_c0` | 1.5666 | 0.7377 | 낙찰배수 절편 ↓ |
| **`M_s`** | **−0.9472** | **0.0** | **낙찰배수가 SOH 와 무관** |
| `M_sd` | 0.5455 | 0.4201 | 낙찰배수 산포 ↓ |
| `p_rc` | 8,708 | 9,491 | 재활용 단가 ↑ |

`M_s = 0` 의 뜻과 근거는 `PriceParams` 독스트링에 남겼다 — 낙찰배수를 SOH 로 회귀하면
R²=0.0008 이고 부호도 반대다. 실제 설명변수는 입찰참가자 수(ln 계수 +0.284)인데 모형
외생이므로 0 으로 두고 로그정규 잡음의 평균만 맞춘다. `Erev` 는 코드 변경 없이 동작한다.

### 캐시 해시 구멍을 함께 막았다 (계획에 없던 수정)

`build()`/`build_stream()` 의 CSR 캐시 키에 **가격 파라미터가 들어 있지 않았다.**
기대 즉시보상 `rsa` 가 캐시에 함께 저장되므로, params.json 만 바꾸고 캐시를 쓰면
**옛 가격으로 푼 답이 아무 경고 없이 나온다.** 이번에 실제로 걸릴 수 있었다.
`_price_key()` 를 넣어 가격을 해시에 포함시키되, w3 가 `_LATE_FIELDS` 에 쓴 요령대로
**구 파라미터와 정확히 같을 때만 키에서 빼서** 기존 379GB 캐시를 v5 재현용으로 살렸다.

> **논문 문장** — "낙찰배수는 SOH 를 거의 설명하지 못한다(R²=0.0008). 낙찰가의 SOH
> 의존성은 전량 예정가격 헤도닉에서 나오고, 낙찰배수를 움직이는 것은 입찰참가자 수다."

## [2] 차종 재선정 — SM3 · 쏘울 · 볼트 · 코나

정밀검사 손익분기 `C_p/q_P` = **973,753원**. 실측 손익배수
`(E[재사용] − p_rc·kWh) / (C_p/q_P)` 로 사다리를 짰다.

| 차종 | 손익배수 | 용량 | SOH중앙 | 실측 REG | 모형 REG (w4) | 모형 REG (v5) |
|---|---:|---:|---:|:--:|:--:|:--:|
| SM3 | 0.05 | 26.6 | 0.670 | R1 | **R1** | R3 ✗ |
| 쏘울 | 0.65 | 30.0 | 0.892 | R1 | **R1** | R2 ✗ |
| 볼트 | 1.99 | 60.0 | 0.969 | R2 | **R2** | R2 ✓ |
| 코나 | 2.89 | 64.0 | 0.861 | R2 | **R2** | R2 ✓ |

분류 임계는 **0.8 / 1.5** 다(`data.reg_from_ratio`). 1.0 에 붙이지 않은 근거는
손익배수가 낙찰배수 잡음(`M_sd`=0.4201, 로그정규 ±34%) 위에서 잰 중앙값이라
1.0 근방 ±20~50% 는 신호 하나로 부호가 바뀌는 구간이기 때문이다. 그 구간이 R3 다.

**두 분류가 새 파라미터에서 4/4 일치한다** (`Instance.REG_AGREE`). 구 파라미터에서는
SM3·쏘울 둘이 어긋났다. 재캘리브레이션이 실제로 고친 것이 이것이다.

한계를 분명히 해 둔다. 선택된 넷 중 **R3(경계) 차종은 없다** — 0.65 와 1.99 사이가
비어 있다. TASK 가 적었듯 유일한 R3 후보 포터2는 상용차이고 2024년 이후 재사용
4건뿐이라 뺐다. 따라서 "경계 차종에서 무슨 일이 일어나는가" 는 이 인스턴스로
답할 수 없다. 답할 수 있는 것은 손익분기 **양쪽**에서의 행동 차이다.

**설계 부작용 하나.** SM3·쏘울이 모형에서도 R1 이 되면서 지배 가지치기(`DUMP`)에
걸려 즉시매각이 강제된다. 이는 `max_b V^PS ≤ V^S` 라는 증명 가능한 지배관계라
최적성을 해치지 않지만, 상태·행동 공간이 크게 줄었다. |T|=4 W=7 의 CSR 이
w3 이 예상한 344GB 가 아니라 **62GB** 로 떨어진 이유가 이것이다.

> **논문 문장** — "실거래 손익배수로 매긴 차종 분류(0.8/1.5 임계)와 모형이 내부적으로
> 매긴 경제영역이 재캘리브레이션 후 네 차종 모두에서 일치한다. 구 파라미터에서는
> 넷 중 둘이 어긋났다."

## [3] 재산출 — W-정식화, |T|=4

상태공간 C(W+16,16). nnz 표본추정을 먼저 돌려 감당 범위를 확정했다.

| W | \|S\| | nnz(추정) | CSR | 실제 | 판정 |
|---:|---:|---:|---:|---:|---|
| 4 | 4,845 | 1.45e7 | 0.2GB | 0.115GB | in-RAM |
| 5 | 20,349 | 8.21e7 | 1.0GB | 1.06GB | in-RAM |
| 6 | 74,613 | 8.93e8 | 10.7GB | 8.57GB | 스트리밍 |
| 7 | 245,157 | 5.18e9 | 62.2GB | 61.9GB | 스트리밍 |
| 8 | 735,471 | 4.36e10 | **523.8GB** | — | **불가** (여유 448GB) |

W=8 은 추정 CSR 이 빈 디스크(448GB)를 넘어 돌리지 않았다. TASK 의 예상과 같다.

### (a) g\* 와 한계가치

| W | \|S\| | g\* | Δg\*/ΔW | 기존 \|T\|=3 의 Δg\* (참고) |
|---:|---:|---:|---:|---:|
| 4 | 4,845 | 3,854,564 | — | — |
| 5 | 20,349 | 3,918,045 | 63,481 | 91,691 |
| 6 | 74,613 | 3,955,859 | 37,814 | 58,989 |
| 7 | 245,157 | 3,977,934 | 22,075 | 35,891 |

한계가치가 단조 감소한다(63,481 → 37,814 → 22,075). 기존 |T|=3 인스턴스의
체감 양상(91,691 → 58,989 → 35,891)과 같은 모양이다. W=7 에서 창고 한 칸의
값은 g\* 의 0.55% 로 떨어져, 이 규모에서 이미 수확체감 구간에 들어와 있다.


### (b) 벤치마크 갭과 관행 손실의 분해

| W | B1 | B2 | INDEX | B_fast | B_fast_hold | = 전량검사 강제 | + 즉시처분 강제 |
|---:|---:|---:|---:|---:|---:|---:|---:|
| 4 | 56.37% | 14.94% | 4.25% | **7.125%** | 3.259% | 3.259%p | 3.867%p |
| 5 | 57.07% | 16.32% | 5.82% | **6.696%** | 4.554% | 4.554%p | 2.141%p |
| 6 | 57.48% | 17.12% | 6.79% | **6.982%** | 5.486% | 5.486%p | 1.496%p |
| 7 | 57.72% | 17.58% | 7.38% | **7.383%** | 6.076% | 6.076%p | 1.306%p |

모든 W 에서 `B_fast` 최적 임계는 thr=0, `B_fast_hold` 도 thr=0 이다 — w3 [2](a) 가
확인한 구조(thr 을 올리면 유일한 정밀 슬롯을 비워 둘 뿐)가 새 인스턴스에서도 같다.

**w3 [2](b) 의 핵심 주장이 재현된다.** 창고가 커질수록 즉시처분 강제의 비용은
3.867 → 1.306%p 로 **줄고**, 전량검사 강제의 비용은 3.259 → 6.076%p 로 **는다**.
W=4 에서는 즉시처분 쪽이 더 컸는데 W=5 부터 전량검사 쪽이 역전한다 —
구 인스턴스(v5, |T|=3)에서는 W=4 에서 이미 전량검사 쪽이 컸으니, 교차점이
창고 한 칸만큼 뒤로 밀렸을 뿐 방향은 같다.

**INDEX 가 B_fast 를 따라잡는다.** W=7 에서 INDEX 7.378% vs B_fast 7.383% 로
사실상 동률이다. 구 인스턴스에서는 INDEX 가 8.4%p 열등했다. 결정이 필요한 차종이
둘뿐이면 근시안 지표의 손해가 거의 사라진다는 뜻이다.


### (c) 강제매각

| W | 최적: 대수/기간 | 가치 | 발동확률 | B_fast: 대수/기간 | 가치 |
|---:|---:|---:|---:|---:|---:|
| 4 | 1.4159 | 528,020원 | 81.54% | 1.1208 | 406,708원 |
| 5 | 0.9899 | 352,490원 | 65.59% | 0.5371 | 182,330원 |
| 6 | 0.6382 | 218,016원 | 47.76% | 0.1634 | 52,320원 |
| 7 | 0.3608 | 119,987원 | 29.23% | 0.0225 | 6,864원 |

최적정책의 강제매각은 W=4 에서 1.4159대/기간(발동확률 81.5%)이던 것이 W=7 에서
0.3608대(29.2%)로 줄지만 **0 이 되지 않는다.** 반면 B_fast 는 0.0225대로 거의
사라진다 — B_fast 는 정의상 선별완료품을 즉시 다 팔아 자리를 비워 두기 때문이다.
최적정책이 강제매각을 감수하면서까지 보유를 택한다는 것이, 갭의 즉시처분 성분이
0 이 되지 않는 이유다.


### (d) 정책 구조 — 선별은 퍼지는가

차종별 행동 비율 — 정상분포 가중, 대/기간. `policy_structure_w4.csv` 전문.

**W=7 (\|S\|=245,157, g\*=3,977,934)**

| 차종 | 실측배수 | REG | 도착 | 취급 | 매각 | 신속 | 정밀직행 | 선별정밀 | 신속률 | 정밀률 |
|---|---:|:--:|---:|---:|---:|---:|---:|---:|---:|---:|
| SM3 | 0.05 | R1 | 0.9538 | 0.7317 | 0.7317 | 0.0000 | 0.0000 | 0.0000 | 0.0% | 0.0% |
| 쏘울 | 0.65 | R1 | 0.4103 | 0.3550 | 0.3550 | 0.0000 | 0.0000 | 0.0000 | 0.0% | 0.0% |
| 볼트 | 1.99 | R2 | 0.8923 | 0.8281 | 0.0000 | 0.8242 | 0.0039 | 0.5150 | 99.5% | 62.7% |
| 코나 | 2.89 | R2 | 1.3436 | 1.3245 | 0.0000 | 1.3226 | 0.0020 | 0.4790 | 99.9% | 36.3% |

정밀 슬롯(CAP=1) 사용률 99.98%. 차종별 점유는 **볼트 51.9% / 코나 48.1%** 다.
신속검사 점유는 **코나 61.6% / 볼트 38.4%**.

### 선별은 퍼지는가 — 답: 퍼진다. 다만 "중간" 이 아니다.

| W | 신속검사 점유 (코나/볼트) | 정밀 슬롯 점유 (코나/볼트) |
|---:|---|---|
| 4 | 69.5% / 30.5% | 59.9% / 40.1% |
| 5 | 65.6% / 34.4% | 54.5% / 45.5% |
| 6 | 63.1% / 36.9% | 50.5% / 49.5% |
| 7 | 61.6% / 38.4% | 48.1% / 51.9% |

w2 에서 "신속검사의 99% 가 코나" 였던 것이 여기서는 **62 대 38** 로 갈라진다.
창고가 커질수록 더 고르게 갈라지고, 정밀 슬롯은 W=6~7 사이에서 아예 **역전**한다
(코나 50.5% → 48.1%). w2 의 집중은 모형 결함이 아니라 인스턴스에 손익분기 위쪽
차종이 하나뿐이었던 데서 온 것이 맞다.

**그러나 "선별은 가치 사다리 중간에만 남는다" 는 형태로는 서지 않는다.**
선별이 0 인 곳은 사다리의 *아래* 둘(SM3 0.05, 쏘울 0.65)이고, 선별이 몰리는 곳은
*위* 둘(볼트 1.99, 코나 2.89)이다. 중간이 아니라 위쪽이다. 이 인스턴스에는
R3(경계) 차종이 아예 없으므로 "중간" 을 직접 시험한 것도 아니다.

고쳐 세운 주장은 이렇다.

> 선별(신속검사)은 **정밀검사가 이득인 차종이 둘 이상이고 정밀 자원이 희소할 때**
> 필요해진다. 손익분기 아래 차종에는 선별할 값이 없고(즉시 매각이 지배),
> 후보가 하나뿐이면 선별할 필요가 없다(어차피 그 하나에 준다).
> 선별의 값은 **후보들 사이의 순위를 다투는 데**서 나온다.

이 재정식화는 위 표가 직접 지지한다 — W 가 커져 강제매각이 줄고 실제 후보가
많아질수록 두 차종의 점유가 50:50 에 가까워진다. 경쟁이 치열해질수록 선별이
고르게 퍼진다는 뜻이다.

정밀직행(`pu`, 신속검사를 건너뛰고 바로 정밀로 보내는 행동)은 W 와 함께 사라진다 —
볼트 기준 0.0456(W=4) → 0.0229 → 0.0096 → 0.0039(W=7). 창고가 좁아 자리를 빨리
비워야 할 때만 조금 쓰이고, 자리가 넉넉해지면 언제나 신속검사를 먼저 통과시키는
것이 낫다. C_f=2만원에 비해 신호의 값이 크기 때문이다.

> **논문 문장** — "손익분기 위쪽에 차종이 둘 있으면 선별은 한 차종에 몰리지 않는다.
> 창고 용량이 커져 후보가 늘수록 두 차종의 선별 점유는 50:50 에 가까워지고,
> 정밀검사 슬롯의 배분은 W=6 과 W=7 사이에서 역전한다. 선별의 값은 검사 자체가
> 아니라 희소한 정밀검사 자원을 두고 다투는 후보들의 순위를 매기는 데서 나온다."


### (e) 학습정책 (carry 디코더, 시드 3개)

`run_w_dcl.py`, 6라운드 × 40에폭, 초기정책은 INDEX. 갭은 g\* 대비 %.

| W | \|S\| | 시드0 | 시드1 | 시드2 | 평균 | 시드당 시간 |
|---:|---:|---:|---:|---:|---:|---:|
| 4 | 4,845 | 0.1037% | 0.0216% | 0.0848% | **0.0700%** | 31s |
| 5 | 20,349 | 6.3e-04% | 1.0e-03% | 8.1e-04% | **8.2e-04%** | 87s |
| 6 | 74,613 | 6.3e-07% | 3.3e-10% | 1.6e-05% | **5.4e-06%** | 402s |
| 7 | 245,157 | 2.9e-06% | −2.3e-14% | 7.0e-14% | **9.8e-07%** | 921s |

**사전등록 기준 1% 를 전 구간에서 크게 밑돈다.** W=4 의 0.07% 가 최악이고,
W≥5 부터는 갭이 1e-3% 아래로 떨어진다. W=7 시드1 은 −2.3e-14% 로 **정확해를
부동소수점 정밀도까지 재현**한다(음수 부호는 스트리밍 평가의 수치잡음이지
학습정책이 최적을 넘은 것이 아니다 — 평균보상 MDP 에서 그럴 수 없다).

W 가 커질수록 갭이 **작아지는** 것은 역설이 아니다. W 가 크면 강제매각이 줄어
상태분포가 넓게 퍼지고, 그만큼 학습 표본이 정상분포의 실제 지지집합을 잘 덮는다.
반대로 W=4 는 상태가 적지만 분포가 몇 개 상태에 몰려 있어 나머지에서 오차가 남는다.

수렴 경로(W=7, 시드0)를 보면 라운드 4 안에 닫힌다.

```
r0: π 7.378% → 개선 2.144% | 신경망 2.144% (행동일치 95.7%)
r1: π 2.144% → 개선 0.052% | 신경망 0.077% (98.5%)
r2: π 0.052% → 개선 0.003% | 신경망 0.003% (99.6%)
r3: π 0.003% → 개선 0.000% | 신경망 0.000% (100.0%)
```

INDEX(7.378%)에서 출발해 세 라운드 만에 정확해에 붙는다. 행동 일치율이 100.0%
(소수 첫째 자리까지)에 이르는 라운드가 나온다는 것이, 이 정책이 Deep Sets 구조로
**표현 가능**하다는 방향의 증거다 — w2 가 남긴 "표현가능 상한" 숙제에 대한 부분적
답이다. 다만 일치율은 정상분포 가중이 아니라 전 상태 균등 기준이고, 라운드 4·5 에서
99.7%·99.4% 로 다시 내려가므로 "완전히 표현 가능하다" 고까지는 말할 수 없다.

legacy 디코더는 TASK 지시대로 생략했다 (w3 [3] 에서 결론이 났다).

> **논문 문장** — "정확해가 가능한 최대 인스턴스(W=7, \|S\|=245,157)에서 학습정책의
> 최적 대비 갭은 시드 3개 평균 9.8e-07% 이며, 한 시드는 부동소수점 정밀도까지
> 정확해를 재현한다. 사전등록 기준 1% 를 네 자릿수 이상 밑돈다."


## [4] 실증 검증

→ `validation.md` (별도 문서). 요지만 옮기면:

- **가격**: 재사용 낙찰단가 예측의 중앙편의 +65.1% → +10.7%, 중앙절대오차 65.2% → 28.9%
  (TASK 가 94건 전수로 낸 값). 손에 넣을 수 있는 4개 차종에서는 +79.7% → +8.3%.
- **배율**: 구 파라미터는 전 차종에서 실측을 크게 웃돌았다. 새 파라미터에서는 편의가
  양방향으로 흩어진다. 다만 `p_rc` 를 차종 무관 상수로 두는 단순화가 대용량 팩의
  재활용 가치를 과소평가한다는 잔여 문제가 남는다(코나 기준 1.76배).
- **구조**: 가격을 보지 않고 푼 최적정책이, 독립 계산한 실측 손익배수가 손익분기
  아래로 놓은 두 차종에 정밀검사를 **한 번도** 배정하지 않는다. 4/4 일치.
  강도 서열은 켄달 타우 +0.600, 유일한 역전은 볼트·코나 한 쌍이다.

## 구 결과와의 대조 — 무엇이 바뀌고 무엇이 유지되는가

두 인스턴스는 차종도 가격도 다르므로 **수준은 비교 대상이 아니다.** 비교할 것은 구조다.

### 바뀐 것

| | w2·w3 (\|T\|=3, v5) | w4 (\|T\|=4, 재캘리브레이션) |
|---|---|---|
| B_fast 갭 (W=6) | 14.72% | **6.98%** (절반 이하) |
| INDEX 갭 (W=6) | 23.08% | **6.79%** |
| B2 갭 (W=6) | 27.93% | **17.12%** |
| INDEX 대 B_fast | INDEX 가 8.4%p 열등 | 거의 동률 (INDEX 가 0.20%p 우월) |
| 신속검사 집중도 (W=6) | 코나 99% | 코나 63% / 볼트 37% |
| \|T\|=4 W=7 규모 | 344GB 로 추정, 포기 | **62GB**, 완주 |

갭이 전반적으로 줄어든 것은 모형이 좋아져서가 아니라 **문제가 쉬워졌기 때문**이다.
SM3·쏘울이 R1 으로 확정되면서 실질적으로 결정이 필요한 차종이 둘로 줄었다.
w2 가 보고한 큰 갭에는 "가격이 틀려서 경계에 서 있던 차종들" 의 몫이 섞여 있었다.

### 유지된 것

1. **관행 손실의 분해 방향** — 창고가 커질수록 즉시처분 강제의 비용은 **줄고**
   전량검사 강제의 비용은 **는다**. w3 [2](b) 의 핵심 주장이 새 인스턴스·새 가격에서
   그대로 재현된다. 크기는 절반이지만 부호와 교차 방향이 같다.
2. **한계가치 체감** — Δg\*/ΔW 가 단조 감소한다.
3. **DCL 1% 이내** — carry 디코더가 정확해가 닿는 가장 큰 인스턴스(W=7)까지 갭 1% 이내.
   구 인스턴스와 같은 W 에서 비교하면 오히려 더 낮다 — w3 의 |T|=3 W=7 은 시드 평균
   1.4e-04%(2.5e-04 / 7.8e-06 / 1.7e-04), w4 의 |T|=4 W=7 은 9.8e-07% 다.
   (w3 DIGEST 가 "0.000%" 로 적은 것은 소수 셋째 자리 반올림 표기였다.
   원자료는 `results/w_model/dcl_W7_carry_seed*.json` 에 있다.)
4. **B1 이 압도적으로 나쁘다** — 전량 즉시매각은 여전히 56~58% 갭.

### 철회하거나 고쳐 세워야 하는 것

- w2 의 **"신속검사가 한 차종에 몰린다"** 는 인스턴스의 산물이었다. 손익분기 위쪽에
  차종이 둘이 되자 즉시 갈라진다. 다만 **"선별은 가치 사다리 중간에만 남는다"** 는
  형태로는 서지 않는다. 선별이 남는 곳은 "중간" 이 아니라 **손익분기 위쪽**이고,
  거기서 여럿이 희소한 정밀 슬롯을 두고 경쟁할 때 선별이 필요해진다.
  손익분기 아래 차종에는 선별이 0 이다. 고쳐 세운 주장은 위 [3](d) 에 적었다.

## 돌다 만 것 · 실패한 것

- **W=8 (|T|=4)** — nnz 표본추정 CSR 523.8GB > 빈 디스크 448GB. 돌리지 않았다.
  캐시 379GB 를 지우면 물리적으로는 들어가지만, 그러면 v5 재현이 불가능해지고
  빌드·풀이만 6~8시간이 든다. 얻는 것(Δg\* 한 점)에 비해 값이 맞지 않는다.
- **[4] §1 이 4개 차종에 그친다** — 원자료 xlsx 2종이 이 머신에 없다.
  전수 94건·기간별 분해 불가. → `BLOCKED_w4.md`
- **[4] §2 기간별 분해** — 거래일자 열이 없어 못 했다. 같은 원인.
- **R3(경계) 차종 없음** — 선택된 넷의 손익배수가 0.65 와 1.99 사이에서 비어 있다.
  경계 거동은 이 인스턴스로 답할 수 없다.
- **legacy 디코더 생략** — TASK 지시대로. w3 에서 결론이 이미 났다.
- **w3 잔여 프로세스 종료 실패** — `pkill` 이 이 세션의 자동승인 분류기에 막혔다.
  w3 때 죽은 부모가 남긴 고아 워커 48개가 아직 떠 있다 (최고 경과 16.8시간,
  RSS 합계 실측 **1.90GB**, CPU 0%). 계산에는 영향이 없었다.
  사용자가 `pkill -f spawn_main` 로 지우면 된다.
- **`~/batdiag-cache/stream_e1014f8beaeb85be.tmp` (5.3GB)** — 중단된 w3 빌드의
  잔해다. 어떤 프로세스도 열고 있지 않다. 지워도 된다.
- **w3 잔여 결과 동봉** — `results/w_model/{T4_W5,T4_W6,T5_W5}.json`,
  `dcl_W{7,8}_carry_seed*.json` 은 중단 전에 이미 완주한 w3 산출물이다.
  **구 파라미터(v5)·구 차종**의 결과임에 주의. 버리기 아까워 함께 커밋한다.
